'use strict';

// Azure App Service sets HOSTNAME to the internal worker hostname which resolves
// to the container private IP. Next.js uses it as the bind address, so it would
// listen on the wrong interface and fail the nginx health check. Delete it so
// Next.js falls back to binding on 0.0.0.0.
//
// NOTE: In CI, this file is NOT copied into the standalone output. The standalone
// server.js generated by Next.js is used directly, with HOSTNAME patched via sed
// in web.yml. This file is kept for local `npm start` use only.
delete process.env.HOSTNAME;

const next = require('next');
const http = require('http');

const port = parseInt(process.env.PORT || '3000', 10);

const app = next({ dev: false, dir: __dirname });
const handle = app.getRequestHandler();

app.prepare()
  .then(() => {
    http
      .createServer((req, res) => handle(req, res))
      .listen(port, '0.0.0.0', () => {
        console.log(`> Ready on http://0.0.0.0:${port}`);
      });
  })
  .catch((err) => {
    console.error('Failed to start Next.js:', err);
    process.exit(1);
  });
